//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dysk
    {
        public int IdDysku { get; set; }
        public Nullable<int> IdProduktu { get; set; }
        public string Producent { get; set; }
        public string Rodzaj { get; set; }
        public string Format { get; set; }
        public Nullable<int> Pojemnosc { get; set; }
    
        public virtual Produkt Produkt { get; set; }
    }
}
