//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KartaGraficzna
    {
        public int IdKartyGraficznej { get; set; }
        public Nullable<int> IdProduktu { get; set; }
        public string ProducentKarty { get; set; }
        public string ProducentChipsetu { get; set; }
        public string Chipset { get; set; }
        public Nullable<int> RAM { get; set; }
        public Nullable<int> TaktowanieRdzenia { get; set; }
    
        public virtual Produkt Produkt { get; set; }
    }
}
