//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SklepEntities : DbContext
    {
        public SklepEntities()
            : base("name=SklepEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<Dysk> Dysk { get; set; }
        public virtual DbSet<Firma> Firma { get; set; }
        public virtual DbSet<KartaGraficzna> KartaGraficzna { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<MetodaPlatnosci> MetodaPlatnosci { get; set; }
        public virtual DbSet<OsobaFizyczna> OsobaFizyczna { get; set; }
        public virtual DbSet<PamiecRAM> PamiecRAM { get; set; }
        public virtual DbSet<PlytaGlowna> PlytaGlowna { get; set; }
        public virtual DbSet<PozycjaZamowienia> PozycjaZamowienia { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<Procesor> Procesor { get; set; }
        public virtual DbSet<Produkt> Produkt { get; set; }
        public virtual DbSet<Promocja> Promocja { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Zamowienie> Zamowienie { get; set; }
    }
}
