//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OsobaFizyczna
    {
        public int IdOsobyFizycznej { get; set; }
        public Nullable<int> IdKlienta { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
    
        public virtual Klient Klient { get; set; }
    }
}
