//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PamiecRAM
    {
        public int IdPamieciRAM { get; set; }
        public Nullable<int> IdProduktu { get; set; }
        public string Producent { get; set; }
        public Nullable<int> LacznaPojemnosc { get; set; }
        public string TypPamieci { get; set; }
        public string CzestotliwoscPracy { get; set; }
        public Nullable<int> LiczbaModulow { get; set; }
    
        public virtual Produkt Produkt { get; set; }
    }
}
