//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlytaGlowna
    {
        public int IdPlytyGlownej { get; set; }
        public Nullable<int> IdProduktu { get; set; }
        public string Producent { get; set; }
        public string GniazdoProcesora { get; set; }
        public Nullable<int> SlotyPamieci { get; set; }
        public Nullable<bool> WiFi { get; set; }
        public Nullable<bool> Bluetooth { get; set; }
    
        public virtual Produkt Produkt { get; set; }
    }
}
