//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozycjaZamowienia
    {
        public int IdPozycjiZamowienia { get; set; }
        public Nullable<int> IdZamowienia { get; set; }
        public Nullable<int> IdPromocji { get; set; }
        public Nullable<int> IdProduktu { get; set; }
        public Nullable<int> Ilosc { get; set; }
        public Nullable<decimal> CenaCalkowita { get; set; }
    
        public virtual Produkt Produkt { get; set; }
        public virtual Promocja Promocja { get; set; }
        public virtual Zamowienie Zamowienie { get; set; }
    }
}
