//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkt()
        {
            this.Dysk = new HashSet<Dysk>();
            this.KartaGraficzna = new HashSet<KartaGraficzna>();
            this.PamiecRAM = new HashSet<PamiecRAM>();
            this.PlytaGlowna = new HashSet<PlytaGlowna>();
            this.PozycjaZamowienia = new HashSet<PozycjaZamowienia>();
            this.Procesor = new HashSet<Procesor>();
        }
    
        public int IdProduktu { get; set; }
        public string Kod { get; set; }
        public string Nazwa { get; set; }
        public Nullable<decimal> CenaZakupu { get; set; }
        public Nullable<decimal> CenaSprzedazy { get; set; }
        public Nullable<int> DostepnaIlosc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dysk> Dysk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KartaGraficzna> KartaGraficzna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PamiecRAM> PamiecRAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlytaGlowna> PlytaGlowna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaZamowienia> PozycjaZamowienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procesor> Procesor { get; set; }
    }
}
