//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienie()
        {
            this.PozycjaZamowienia = new HashSet<PozycjaZamowienia>();
        }
    
        public int IdZamowienia { get; set; }
        public Nullable<int> IdKlienta { get; set; }
        public Nullable<int> IdMetodyPlatnosci { get; set; }
        public Nullable<System.DateTime> DataZlozenia { get; set; }
        public Nullable<int> IdStatusu { get; set; }
        public Nullable<decimal> KwotaZamowienia { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual MetodaPlatnosci MetodaPlatnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaZamowienia> PozycjaZamowienia { get; set; }
        public virtual Status Status { get; set; }
    }
}
